export { startProxy, startGateway, createProxyServer, createGatewayServer } from "./proxy.js";
export { elicitationApprover, dashboardApprover, chainApprovers } from "./gateway/approval.js";
export type { Approver, ApprovalRequest, ApprovalOutcome, ApprovalChannel } from "./gateway/approval.js";
export { PiiVault } from "./gateway/tokens.js";
export { maskFields } from "./gateway/fields.js";
export { loadProxyConfig } from "./config.js";
export { loadGatewayConfig, parseGatewayYaml, fromLegacyConfig } from "./gateway/config.js";
export type { GatewayConfig, ListenConfig, PolicySourceConfig } from "./gateway/config.js";
export { Gateway } from "./gateway/gateway.js";
export { clientUpstream, connectStdioUpstream, connectHttpUpstream, connectUpstream } from "./gateway/upstream.js";
export type { Upstream } from "./gateway/upstream.js";
export { labelTool, LABELS } from "./gateway/labels.js";
export type { Label } from "./gateway/labels.js";
export { evaluatePolicy, globToRegExp } from "./gateway/policy.js";
export type { PolicyAction, PolicyRule, PolicyDecision } from "./gateway/policy.js";
export { TaintTracker } from "./gateway/taint.js";
export type { TaintMode, TaintSnapshot } from "./gateway/taint.js";
export { scanForPromptInjection } from "./interceptors/prompt-injection.js";
export { scanToolResult } from "./interceptors/tool-result.js";
export { ToolDefinitionPin } from "./interceptors/definition-drift.js";
export { maskPiiInValue, maskPiiInText } from "./interceptors/pii-masker.js";
export { AuditLogger, verifyAuditChain } from "./audit/logger.js";
export type { ChainVerification } from "./audit/logger.js";
export type { ProxyConfig, McpServerConfig, HttpUpstreamConfig, UpstreamConfig, InterceptResult, AuditEvent, AuditConfig, DashboardSinkConfig } from "./types.js";
export { planInit, runInit, clientConfigPath } from "./init.js";
export type { ClientName, InitPlan, InitOptions, InitResult } from "./init.js";
export { startHttpGateway } from "./http-server.js";
export type { HttpGateway } from "./http-server.js";
export { DashboardSink } from "./audit/dashboard-sink.js";
export { PolicySync } from "./gateway/policy-sync.js";
export type { RefreshResult } from "./gateway/policy-sync.js";
