import fs from "fs";
import os from "os";
import path from "path";
import { stringify as toYaml } from "yaml";
import type { McpServerConfig } from "./types.js";

export type ClientName = "claude-desktop" | "cursor" | "claude-code";

/** Where each client keeps its user-level MCP config. */
export function clientConfigPath(client: ClientName, platform = process.platform, home = os.homedir()): string {
  switch (client) {
    case "claude-desktop":
      if (platform === "darwin") return path.join(home, "Library", "Application Support", "Claude", "claude_desktop_config.json");
      if (platform === "win32") return path.join(process.env["APPDATA"] ?? path.join(home, "AppData", "Roaming"), "Claude", "claude_desktop_config.json");
      return path.join(home, ".config", "Claude", "claude_desktop_config.json");
    case "cursor":
      return path.join(home, ".cursor", "mcp.json");
    case "claude-code":
      return path.join(home, ".claude.json");
  }
}

export interface InitPlan {
  /** guardbee-proxy.yaml contents. */
  yaml: string;
  /** The client config rewritten to launch the proxy. */
  clientConfig: string;
  /** Server entries moved behind the proxy: config key → upstream name. */
  migrated: Record<string, string>;
  /** Entries left in the client config, and why. */
  kept: { name: string; reason: string }[];
}

const PROXY_PACKAGE = "@guardbee/mcp-security-proxy";

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
}

function isProxyEntry(entry: Record<string, unknown>): boolean {
  const words = [entry["command"], ...(Array.isArray(entry["args"]) ? entry["args"] : [])].map(String);
  return words.some((word) => word.includes(PROXY_PACKAGE) || /(^|[/\\])guardbee-proxy(\.cmd)?$/.test(word));
}

/** Config keys become upstream names: letters, digits, - and single _. */
function upstreamName(key: string, taken: Set<string>): string {
  const base =
    key
      .replace(/[^A-Za-z0-9_-]+/g, "-")
      .replace(/_{2,}/g, "_")
      .replace(/^[_-]+|[_-]+$/g, "") || "server";
  let name = base;
  for (let i = 2; taken.has(name); i++) name = `${base}-${i}`;
  taken.add(name);
  return name;
}

function stringRecord(value: unknown): Record<string, string> | undefined {
  const rec = asRecord(value);
  if (!rec) return undefined;
  const out = Object.fromEntries(
    Object.entries(rec).flatMap(([k, v]) => (typeof v === "string" || typeof v === "number" || typeof v === "boolean" ? [[k, String(v)]] : [])),
  );
  return Object.keys(out).length > 0 ? out : undefined;
}

/**
 * Work out the migration without touching the disk. stdio servers move into
 * the YAML; HTTP servers, disabled entries and an existing proxy entry stay.
 */
export function planInit(clientConfigText: string, yamlPath: string, auditPath: string): InitPlan {
  const root = asRecord(JSON.parse(clientConfigText));
  if (!root) throw new Error("The client config is not a JSON object");
  const servers = asRecord(root["mcpServers"]);
  if (!servers || Object.keys(servers).length === 0) throw new Error("No mcpServers found in the client config");

  const upstreams: Record<string, McpServerConfig> = {};
  const migrated: Record<string, string> = {};
  const kept: InitPlan["kept"] = [];
  const remaining: Record<string, unknown> = {};
  const taken = new Set<string>();

  for (const [key, value] of Object.entries(servers)) {
    const entry = asRecord(value);
    if (!entry) {
      remaining[key] = value;
      kept.push({ name: key, reason: "not an object" });
    } else if (isProxyEntry(entry)) {
      remaining[key] = value;
      kept.push({ name: key, reason: "already the GuardBee proxy" });
    } else if (entry["disabled"] === true) {
      remaining[key] = value;
      kept.push({ name: key, reason: "disabled" });
    } else if (typeof entry["command"] !== "string") {
      remaining[key] = value;
      kept.push({ name: key, reason: "HTTP server: the proxy does not front HTTP servers yet, so this one bypasses the policy" });
    } else {
      const name = upstreamName(key, taken);
      const args = Array.isArray(entry["args"]) ? entry["args"].map(String) : undefined;
      const env = stringRecord(entry["env"]);
      upstreams[name] = { command: entry["command"], ...(args?.length ? { args } : {}), ...(env ? { env } : {}) };
      migrated[key] = name;
    }
  }
  if (Object.keys(upstreams).length === 0) throw new Error("No stdio MCP servers to move behind the proxy");

  const proxyKey = !("guardbee" in remaining) ? "guardbee" : "guardbee-gateway";
  // Pinned to 1.x: 0.x does not understand --config and would fail to start.
  remaining[proxyKey] = { command: "npx", args: ["-y", `${PROXY_PACKAGE}@^1`, "--config", yamlPath] };

  const yaml =
    "# GuardBee MCP gateway — generated by `guardbee-proxy init`.\n" +
    "# Tools appear to the agent as <upstream>__<tool>. Check a change with `guardbee-proxy validate --config <this file>`.\n" +
    "# env values were copied from the client config; move secrets to ${VAR} references where you can.\n" +
    toYaml({
      version: 1,
      upstreams,
      taint: { mode: "strict" },
      audit: { sink: "file", filePath: auditPath },
    });

  return {
    yaml,
    clientConfig: JSON.stringify({ ...root, mcpServers: remaining }, null, 2) + "\n",
    migrated,
    kept,
  };
}

export interface InitOptions {
  clientConfigPath: string;
  yamlPath: string;
  dryRun?: boolean;
  force?: boolean;
  now?: Date;
}

export interface InitResult extends InitPlan {
  backupPath?: string;
}

/** Write the YAML (mode 0600, it may hold tokens), back up the client config, then rewrite it. */
export function runInit(options: InitOptions): InitResult {
  const clientPath = path.resolve(options.clientConfigPath);
  const yamlPath = path.resolve(options.yamlPath);
  const auditPath = path.join(path.dirname(yamlPath), "guardbee-audit.jsonl");
  if (!fs.existsSync(clientPath)) throw new Error(`Client config not found: ${clientPath}`);
  if (fs.existsSync(yamlPath) && !options.force && !options.dryRun) {
    throw new Error(`${yamlPath} already exists; pass --force to overwrite it`);
  }

  const plan = planInit(fs.readFileSync(clientPath, "utf8"), yamlPath, auditPath);
  if (options.dryRun) return plan;

  const stamp = (options.now ?? new Date()).toISOString().replace(/[:.]/g, "-");
  const backupPath = `${clientPath}.guardbee-backup-${stamp}`;
  fs.mkdirSync(path.dirname(yamlPath), { recursive: true });
  fs.writeFileSync(yamlPath, plan.yaml, { mode: 0o600 });
  fs.chmodSync(yamlPath, 0o600); // `mode` only applies when the file is created; --force may overwrite a wider one

  fs.copyFileSync(clientPath, backupPath);
  fs.writeFileSync(clientPath, plan.clientConfig);
  return { ...plan, backupPath };
}
